#!/usr/bin/env sh
API_WORKSPACE_LINK="/config/workspace/api"

if [ "$(id -u)" -eq 1000 ]; then
  echo USER OK
  echo Installing package in VENV
  . /config/venv/bin activate
  while true; do
    echo trying to install package
    pyproject=$(find /config/workspace -name pyproject.toml)
    if [ -f "${pyproject}" ]; then
      echo trying to install ${pyproject}
      rm -rf "${API_WORKSPACE_LINK}"
      echo trying to link
      ln -s "$(basename $(dirname ${pyproject}))" "${API_WORKSPACE_LINK}"
      cd "${API_WORKSPACE_LINK}" || echo ERROR changing into app directory
      /config/venv/bin/pip install -e .[lint,test] && break
    else
      still no project found
    fi
    sleep 10
    echo failed, retrying
  done
else
  echo switching USER
  if [ ! -e "${API_WORKSPACE_LINK}" ]; then
    echo creating dummy API Workspace folder ${API_WORKSPACE_LINK}
    mkdir "${API_WORKSPACE_LINK}"
    echo Clone api repository to /config/workspace/ >> "${API_WORKSPACE_LINK}/README.md"
  fi
  chown -R abc:abc /config/
  sudo -u abc $0 $*
fi
