#!/usr/bin/env sh

if [ "$(id -u)" -eq 1000 ]; then
  echo USER OK
  echo Installing package in VENV
  . /config/venv/bin activate
  cd /config/workspace
  while true; do
    echo trying to install package
    /config/venv/bin/pip install -e .[lint,test] && break
    sleep 10
    echo failed, retrying
  done
else 
  echo switching USER
  sudo -u abc $0 $*
fi

