#!/usr/bin/env sh

echo Installing package in VENV

. /config/venv/bin activate

while true; do
  echo trying to install package
  pip install -e .[lint|test] && break
  sleep 10
  echo failed, retrying
done


