#!/usr/bin/env sh

echo run CALLED

echo INSTALLING PLUGINS
rm -rf /config/extensions

for extension in  $(cat $(dirname $0)/extensions.txt); do
  install-extension ${extension}
done

echo DONE INSTALLING PLUGINS

chown -R root:root /config/extensions/extensions.json
chmod 644 /config/extensions/extensions.json


