#!/usr/bin/env sh

echo run CALLED

echo INSTALLING PLUGINS
chmod 777 /config/extensions

for extension in  $(cat $(dirname $0)/extensions.txt); do
  if (echo ${extension} | grep "^#"); then
    echo SKIPPING ${extension}
  else
    install-extension ${extension}
  fi
done

echo DONE INSTALLING PLUGINS

chown -R root:root /config/extensions/extensions.json
chmod 644 /config/extensions/extensions.json
